### ISSUE TITLE
Add a "Books" page

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-charney#6]

**Comment by nuritgazit** [comment]
Waiting for materials fro Limei and then or design

**Comment by Netush** [comment]
Design Ready:
https://projects.invisionapp.com/d/main#/console/9450514/232115243/preview

**Comment by TheGrandVizier** [comment]
We got the stuff from Limei, yes? @nuritgazit

**Comment by nuritgazit** [comment]
We got the images and links, and about text should be taken from Amazon. I will forward you the email

**Comment by nirgoldberg** [comment]
Done.

**Comment by nuritgazit** [comment]
Thanks. Please check the amount of books - I think we are missing a few

**Comment by nuritgazit** [comment]
Closing, as this is now content issues, that can be handled via admin. @TheGrandVizier please add to Trello and assign Danna
