### ISSUE TITLE
Add images to timeline

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/wp-charney#7]
Add images to timeline based on 3 personal albums sent by Limei.

https://www.dropbox.com/work/Hatfutsot/Samples/_Photo%20Books

**Comment by nuritgazit** [comment]
@TheGrandVizier Neta and Ushi had a correspondence re these images, please understand status / assign them on this
(Ushi is the one adding the images, not Nir)

**Comment by nuritgazit** [comment]
@Netush please approve images

**Comment by Netush** [comment]
1956  The vigorous student - **Image Approve** but remove grey frame
1960  The Do-Gooder - **Update image** and remove grey frame
1971  The Celebrities attorney - **Image Approve** but remove grey frame
1975  The Warmhearted Jew - **Image Approve** but remove grey frame
1979  The Peace Architect - **Update image** and remove grey frame
1980  Manhattan’s Real Estate King - **Image Approve**
1984  Back door Channels - **Image Approve** but remove grey frame
1988  T.V. Host - **Image Approve** but remove grey frame 
1991  Family Man - **Update image** and remove grey frame
2006  A scholar of Jewish Culture - **Image Approve** but remove grey frame
2016  An Advocate and philanthropist to the end - **Update image** 

All Images can be Found here:
https://www.dropbox.com/sh/5xik9d54kljmmkg/AAA5fP1bBuABeOTH_h6-KzkGa?dl=0

**Comment by nuritgazit** [comment]
Thank you, @Netush
